version: '3'

services:
  app:
    build:
      context: .
      args:
        - POSTGRES_HOST=supergym_db
        - POSTGRES_PWD=password
    container_name: api_supergym
    command: yarn dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    image: postgres
    container_name: supergym_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supergym_db
    volumes:
      - .:/usr/app/
    working_dir: /usr/app
