version: '3'

services:
  app:
    build: .
    container_name: api_supergym
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    image: postgres
    container_name: supergym_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supergym_db
    volumes:
      - .:/usr/app/
    working_dir: /usr/app
