version: '3'

services:
  app:
    build:
      context: .
    container_name: api_supergym
    command: yarn dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    image: postgres
    container_name: supergym_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - .:/usr/app/
    working_dir: /usr/app
