name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x

      - name: Install dependencies
        run:  yarn install

      - name: Run containers
        run:  docker compose up

      - name: Sync database
        run: |
          docker-compose exec -it app sh -c "yarn prisma migrate dev"

      - name: Test
        run: yarn test
 
        env:
          CI: true
          DB_HOST: supergym_db
          DB_USER: postgres
          DB_PASSWORD: password

      - name: Stop services
        run: docker-compose down
