name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Database

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x

      - name: Creat .env file
        uses: ozaytsev86/create-env-file@v1
        with:
            ENV_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            ENV_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            ENV_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
            ENV_DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Install dependencies
        run: yarn install

      - name: Up Containers
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: docker-compose up -d
          
      - name: Migrations
        run: docker exec -i api_supergym sh -c "yarn prisma migrate dev"

      - name: Test
        env:
          CI: true
        run: docker exec -i api_supergym sh -c "yarn test"
        
      - name: Containers logs
        run: docker-compose logs

      - name: Stop services
        run: docker-compose down




      
