name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Up Containers
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: supergym_db
          DATABASE_URL: postgresql://postgres:password@supergym_db:5432/supergym_db?schema=public
        run: docker-compose up -d
          
      - name: Migrations
        run: docker exec -it -t api_supergym sh -c "yarn prisma migrate dev"


      - name: Test
        env:
          CI: true
        run: yarn test
        
      - name: Containers logs
        run: docker-compose logs

      - name: Stop services
        run: docker-compose down




      
