name: CI - Unit

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Database

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Test
        env:
          CI: true
        run: yarn test __tests__/unit
        




      
